/*
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
Tags: Hash Table Bit Manipulation
Similar Problems: (E) Single Number
*/
#include "I_Struct.h"
class Solution {
public:
	char findTheDifference(string s, string t) 
	{
		map<char, int> sMap;
		for (int i=0; i<s.size(); i++)
		{
			char ch = s[i];
			sMap[ch]++;
		}

		map<char, int> tMap;
		for (int i=0; i<t.size(); i++)
		{
			char ch = t[i];
			tMap[ch]++;
		}
		map<char, int>::iterator it_s = sMap.begin();
		map<char, int>::iterator it_t = tMap.begin();
		map<char, int>::iterator it_t_end = tMap.end();
		for (; it_t != it_t_end; it_s++, it_t++)
		{
			if ((it_s->first != it_t->first) || (it_s->second != it_t->second))
			{
				return it_t->first;
			}
		}
		return NULL;
	}
};